---
- name: "Run Level 2 Tasks"
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "sudo_password"

  vars_files:
    - vars/main.yml
    
  tasks:
    # Section 1 - Include all files
    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.4.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.5.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.6.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.7.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.8.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.1.9.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.4.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.5.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.6.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.7.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.8.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.9.yml
      tags: level2-server, level2-workstation

    - name: Include Section 1 tasks for Level 2
      include_tasks: tasks/section_1/cis_1.10.yml
      tags: level2-server, level2-workstation

    # Section 2 - Include all files
    - name: Include Section 2 tasks for Level 2
      include_tasks: tasks/section_2/cis_2.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 2 tasks for Level 2
      include_tasks: tasks/section_2/cis_2.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 2 tasks for Level 2
      include_tasks: tasks/section_2/cis_2.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 2 tasks for Level 2
      include_tasks: tasks/section_2/cis_2.4.yml
      tags: level2-server, level2-workstation

    # Section 3 - Include all files
    - name: Include Section 3 tasks for Level 2
      include_tasks: tasks/section_3/cis_3.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 3 tasks for Level 2
      include_tasks: tasks/section_3/cis_3.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 3 tasks for Level 2
      include_tasks: tasks/section_3/cis_3.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 3 tasks for Level 2
      include_tasks: tasks/section_3/cis_3.4.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 3 tasks for Level 2
      include_tasks: tasks/section_3/cis_3.4.2.x.yml
      tags: level2-server, level2-workstation

    # Section 4 - Include all files
    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.1.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.1.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.1.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.1.4.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.2.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.2.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.2.3.yml
      tags: level2-server, level2-workstation

    - name: Include Section 4 tasks for Level 2
      include_tasks: tasks/section_4/cis_4.3.yml
      tags: level2-server, level2-workstation

    # Section 5 - Include all files
    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.2.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.3.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.4.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.5.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.5.x_authselect.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.6.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 5 tasks for Level 2
      include_tasks: tasks/section_5/cis_5.6.1.x.yml
      tags: level2-server, level2-workstation

    # Section 6 - Include all files
    - name: Include Section 6 tasks for Level 2
      include_tasks: tasks/section_6/cis_6.1.x.yml
      tags: level2-server, level2-workstation

    - name: Include Section 6 tasks for Level 2
      include_tasks: tasks/section_6/cis_6.2.x.yml
      tags: level2-server, level2-workstation

  handlers:
    - include: handlers/main.yml
