---

# This task is used to create variables used in giving a warning summary for manual tasks
# that need attention
#
# The warn_control_list and warn_count vars start life in vars/main.yml but get updated
# as the tasks that have a warning complete
#
# Those two variables are used in the tasks/main.yml to display a list of warnings
#
# warn_control_id is set within the task itself and has the control ID as the value
#
# warn_control_list is the main variable to be used and is a list made up of the warn_control_id’s
#
# warn_count the main variable for the number of warnings and each time a warn_control_id is added

# Set the warn_control_id (you may need to define this in vars or as a task)
- name: Set warn_control_id for the current task
  ansible.builtin.set_fact:
    warn_control_id: "control4"  # Example ID, modify as needed

# the count increases by a value of 1
- name: "{{ warn_control_id }} | AUDIT | Set fact for manual task warning."
  ansible.builtin.set_fact:
      warn_control_list: "{{ warn_control_list + [warn_control_id] }}"
      warn_count: "{{ (warn_count | default(0)) | int + 1 }}"
