- name: "1.10 | PATCH | Ensure system-wide crypto policy is not legacy"
  block:
    - name: "1.10 | PATCH | Gather current system-wide crypto policy"
      ansible.builtin.shell: |
        update-crypto-policies --show
      register: rockylinux9cis_system_wide_crypto_policy

    - name: "1.10 | PATCH | Ensure system-wide crypto policy is not legacy | set_fact"
      ansible.builtin.set_fact:
        rockylinux9cis_full_crypto_policy: >
          {{ rockylinux9cis_crypto_policy }}{% if rockylinux9cis_crypto_policy_module is defined and rockylinux9cis_crypto_policy_module is not none and rockylinux9cis_crypto_policy_module | length > 0 %}:{{ rockylinux9cis_crypto_policy_module }}{% endif %}

    - name: "1.10 | PATCH | Ensure system-wide crypto policy is not legacy"
      ansible.builtin.shell: |
        update-crypto-policies --set "{{ rockylinux9cis_full_crypto_policy }}"
        update-crypto-policies
      notify: Change_requires_reboot
      when:
        - rockylinux9cis_system_wide_crypto_policy.stdout != rockylinux9cis_full_crypto_policy
  when:
    - rockylinux9cis_rule_1_10

  tags:
    - level1-server
    - level1-workstation
    - automated
    - no system_is_ec2
    - patch
    - rule_1.10
